#!/bin/sh
set -e
APP_DIR=/srv/unglobalcompact/current
RAILS_ENV=production

PATH=/usr/local/bin:$PATH
(date && cd $APP_DIR && nice -n19 bundle exec rails runner -e $RAILS_ENV "Redesign::Searchable.index_new_or_updated") >> $APP_DIR/log/cron-searchable.log 2>&1
