#!/bin/sh
DATE=`date "+20%y_%m_%d"`
# dump table and data for everything but the searchables and sessions tables
sudo mysqldump --opt -u root unglobalcompact --ignore-table=unglobalcompact.sessions --ignore-table=unglobalcompact.searchables | gzip > /home/rails/ungc/mysql_dumps/production_unglobalcompact_$DATE.sql.gz

# dump just the table definitions for searchables and sessions
sudo mysqldump --opt --no-data -u root unglobalcompact sessions searchables | gzip > /home/rails/ungc/mysql_dumps/sessions_and_searchables_tables.sql.gz
