# Blue
dark-blue:    "#1e3250"
blue:         "#4c6b8b"
light-blue:   "#699cc6"
pastel-blue:  "#aecfe6"

# Teal
# darker-teal:  "#0b1f26" # Styleguide, Page 21
# dark-teal:    "#004d65"
# teal:         "#00979e"
# light-teal:   "#8fd2ca"

# Teal is now the updated purple
darker-teal:  "#93679c"
dark-teal:    "#93679c"
teal:   	  "#93679c"
light-teal:   "#bea3c3"

# Green
dark-green:   "#009e77"
green:        "#009e77"
light-green:  "#50b293"

# Red
dark-red:     "#ee4d56"
red:          "#ef7278"
light-red:    "#f2949a"
pastel-red:   "#f5b8bc"

# Orange
dark-orange:  "#f6ad38"
orange:       "#f6ad38"
light-orange: "#f8bd61"

# Gold
gold: "#CBB248"

# Old Grey
#dark-grey:    "#3f3f3f"
#grey:         "#696973"
#light-grey:   "#a3a3a3"
#blue-grey:    "#e6f8ff"

# New grey
dark-grey:    "#3f3f3f"
grey:         "#b4ada8"
light-grey:   "#d3cecb"
white-grey:   "#e8e8e8"
black-grey:   "4C4C4C"
blue-grey:    "#e0dedb"

# Others
twitter-blue:     "#55acee"
facebook-blue:    "#3b5998"
google-plus-red:  "#dd4b39"
linkedin-blue:    "#0077b5"
