universal: &universal
  ungc_organization_name: 'UNGC'
  local_network_guest_name: 'Local Network Guests'
  url_host: 'unglobalcompact.org'

development:
  path_to_cop_xml: '../shared/data/cop_xml/*'
  salesforce:
    :host: 'test.salesforce.com'
    :username: 'ben@bitfield.co.fgcfull'
    :password: 'Bitfield1'
    :token: 'Znn0hp3X3D7tnTOrHrV29bCNB'
    :client_id: '3MVG9ifmAKCHISbaTzCrnAlwIXcBD0lDl.yqCOzQFJhNQCyAr_0B6PoOoc98ix.u4kEMe0zM83E3o304wkvTc'
    :client_secret: '4582587186223235381'
    # The only way to push scripts to production are to push to this Sandbox environment first, and publish from there
    # So we set the callback_url to the real one that production will use. Be careful.
    :callback_url: 'https://www.unglobalcompact.org/salesforce/sync'
  <<: *universal

test:
  path_to_cop_xml: 'data/cop_xml'
  salesforce:
    :host: 'fake.salesforce.host'
    :username: 'username'
    :password: 'password'
    :token: 'token'
    :client_id: 'client_id'
    :client_secret: 'client_secret'
    :callback_url: 'https://www.unglobalcompact.org/salesforce/sync'
  <<: *universal

production:
  path_to_cop_xml: '../../shared/data/cop_xml/*'
  salesforce:
    :host: 'na18.salesforce.com'
    :username: 'salesforce@unglobalcompact.org'
    :password: 'UNGC2017!'
    :token: 'zMhu9bdAj9BbTioxOnx1GYou'
    :client_id: '3MVG9yZ.WNe6byQA3.eubyLjVXu.C2uy4iK.BzfJQK._fMp.Uo1fSYe5rOaIfUiCLXOVpLyQjXds2eD6FaoCB'
    :client_secret: '3432384631816779467'
    :callback_url: 'https://www.unglobalcompact.org/salesforce/sync'
  <<: *universal

staging:
  salesforce:
    :host: 'test.salesforce.com'
    :username: 'ben@bitfield.co.fgcfull'
    :password: 'Bitfield1'
    :token: 'Znn0hp3X3D7tnTOrHrV29bCNB'
    :client_id: '3MVG9ifmAKCHISbaTzCrnAlwIXcBD0lDl.yqCOzQFJhNQCyAr_0B6PoOoc98ix.u4kEMe0zM83E3o304wkvTc'
    :client_secret: '4582587186223235381'
    :callback_url: 'https://staging.unglobalcompact.org/salesforce/sync'
  <<: *universal

preview:
  <<: *universal
