universal: &universal
  cop_inactives_path: '/COP/inactives.html'
  cop_noncommunicating_path: '/COP/non_communicating.html'
  cop_notable_path: '/COP/notable_cops.html'
  cop_search_path: '/COP/cop_search.html'
  news_archive_path: '/NewsAndEvents/news_archives/index.html'
  news_headlines_path: '/NewsAndEvents/index.html'
  participant_search_path: '/ParticipantsAndStakeholders/search_participant.html'
  upcoming_events_path: '/NewsAndEvents/Upcoming_Events.html'
  
development:
  test: thing
  <<: *universal
  
test:
  test: thing
  <<: *universal

production:
  test: thing
  <<: *universal

staging:
  test: thing
  <<: *universal
