universal: &universal
  ungc_organization_name: 'UNGC'
  local_network_guest_name: 'Local Network Guests'
  url_host: 'unglobalcompact.org'

development:
  test: thing
  path_to_cop_xml: '../shared/data/cop_xml/*'
  salesforce:
    :host: 'cs18.salesforce.com'
    :username: 'salesforce@unglobalcompact.org.ungc'
    :password: 'ungcsalesf0rce'
    :token: '3G7U31PWfis4pUzLEDObQKGM'
    :client_id: '3MVG9ogKZdEXNjz1r3.A6o1O2hiJM6jng6glEFpyyBpaTrbDzRZSzcwEu_oZbeFGlES3Qoihe3u4u1z4nzqEU'
    :client_secret: '2046699209085755023'
    # The only way to push scripts to production are to push to this Sandbox environment first, and publish from there
    # So we set the callback_url to the real one that production will use. Be careful.
    :callback_url: 'https://www.unglobalcompact.org/salesforce/sync'
  <<: *universal

test:
  test: thing
  path_to_cop_xml: 'data/cop_xml'
  <<: *universal

production:
  test: thing
  path_to_cop_xml: '../../shared/data/cop_xml/*'
  salesforce:
    :host: 'na18.salesforce.com'
    :username: 'salesforce@unglobalcompact.org'
    :password: 'UNGCS4l3sf0rc3'
    :token: 'oBpRASHMnOONWexsNk0yE9tc'
    :client_id: '3MVG9yZ.WNe6byQA3.eubyLjVXqbjVD.LVqC4SvP4zG6qovb77mwdCwgjK3mCXStC2TMqs17Q400NSGt6e.TK'
    :client_secret: '4153199578286720849'
    :callback_url: 'https://www.unglobalcompact.org/salesforce/sync'
  <<: *universal

staging:
  test: thing
  salesforce:
    :host: 'cs18.salesforce.com'
    :username: 'salesforce@unglobalcompact.org.ungc'
    :password: 'ungcsalesf0rce'
    :token: '3G7U31PWfis4pUzLEDObQKGM'
    :client_id: '3MVG9ogKZdEXNjz1r3.A6o1O2hiJM6jng6glEFpyyBpaTrbDzRZSzcwEu_oZbeFGlES3Qoihe3u4u1z4nzqEU'
    :client_secret: '2046699209085755023'
    :callback_url: 'https://staging.unglobalcompact.org/salesforce/sync'
  <<: *universal

preview:
  test: thing
  <<: *universal
