universal: &universal
  ungc_organization_name: 'UNGC'
  local_network_guest_name: 'Local Network Guests'
  url_host: 'unglobalcompact.org'

development:
  path_to_cop_xml: '../shared/data/cop_xml/*'
  salesforce:
    :host: 'test.salesforce.com'
    :username: 'ben@bitfield.co.ungcfull'
    :password: 'ungcsalesf0rce'
    :token: '9iCvBfGrY4U7Gb1GyQvFah8u'
    :client_id: '3MVG9ogKZdEXNjz1r3.A6o1O2hjz9FcnWsqF0haXa8I9qsrI0bn4Tyfx2rHJSbGhzHO4KGrHjHlJNQzOa3Syp'
    :client_secret: '6757790698554189730'
    # The only way to push scripts to production are to push to this Sandbox environment first, and publish from there
    # So we set the callback_url to the real one that production will use. Be careful.
    :callback_url: 'https://www.unglobalcompact.org/salesforce/sync'
  <<: *universal

test:
  path_to_cop_xml: 'data/cop_xml'
  salesforce:
    :host: 'host'
    :username: 'username'
    :password: 'password'
    :token: 'token'
    :client_id: 'client_id'
    :client_secret: 'client_secret'
    :callback_url: 'https://www.unglobalcompact.org/salesforce/sync'
  <<: *universal

production:
  path_to_cop_xml: '../../shared/data/cop_xml/*'
  salesforce:
    :host: 'na18.salesforce.com'
    :username: 'salesforce@unglobalcompact.org'
    :password: 'UNGC2017!'
    :token: 'zMhu9bdAj9BbTioxOnx1GYou'
    :client_id: '3MVG9yZ.WNe6byQA3.eubyLjVXu.C2uy4iK.BzfJQK._fMp.Uo1fSYe5rOaIfUiCLXOVpLyQjXds2eD6FaoCB'
    :client_secret: '3432384631816779467'
    :callback_url: 'https://www.unglobalcompact.org/salesforce/sync'
  <<: *universal

staging:
  salesforce:
    :host: 'test.salesforce.com'
    :username: 'ben@bitfield.co.ungcfull'
    :password: 'ungcsalesf0rce'
    :token: '9iCvBfGrY4U7Gb1GyQvFah8u'
    :client_id: '3MVG9ogKZdEXNjz1r3.A6o1O2hjz9FcnWsqF0haXa8I9qsrI0bn4Tyfx2rHJSbGhzHO4KGrHjHlJNQzOa3Syp'
    :client_secret: '6757790698554189730'
    :callback_url: 'https://staging.unglobalcompact.org/salesforce/sync'
  <<: *universal

preview:
  <<: *universal
