universal: &universal
  ungc_organization_name: 'UNGC'
  url_host: 'unglobalcompact.org'
  search_results_per_page: 25
  case_story_path: '/COP/Case_Story/case_search.html'
  cop_advanced_path: '/COP/analyzing_progress/advanced_cops.html'
  cop_learner_path: '/COP/analyzing_progress/learner_cops.html'
  cop_expelled_path: '/COP/analyzing_progress/expelled_participants.html'
  cop_inactives_path: '/COP/inactives.html'
  cop_noncommunicating_path: '/COP/analyzing_progress/non_communicating.html'
  cop_notable_path: '/COP/analyzing_progress/notable_cops.html'
  cop_search_path: '/COP/cop_search.html'
  news_archive_path: '/NewsAndEvents/news_archives/index.html'
  news_headlines_path: '/NewsAndEvents/index.html'
  participant_search_path: '/participants/search'
  participant_lead_path: '/HowToParticipate/Lead/lead_participants.html'
  search_path: '/search'
  signup_form_path: '/HowToParticipate/How_To_Apply.html'
  upcoming_events_path: '/NewsAndEvents/Upcoming_Events.html'
  
development:
  test: thing
  path_to_cop_xml: '../shared/data/cop_xml/*'
  <<: *universal
  
test:
  test: thing
  path_to_cop_xml: 'data/cop_xml'
  <<: *universal

production:
  test: thing
  path_to_cop_xml: '../../shared/data/cop_xml/*'
  <<: *universal

staging:
  test: thing
  <<: *universal