universal: &universal
  ungc_organization_name: 'UNGC'
  local_network_guest_name: 'Local Network Guests'
  url_host: 'unglobalcompact.org'
  salesforce:
    :debug: false
    :api_version: "41.0"
    # The only way to push scripts to production are to push to this Sandbox environment first, and publish from there
    # So we set the callback_url to the real one that production will use. Be careful.
    :callback_url: 'https://www.unglobalcompact.org/salesforce/sync'

development:
  <<: *universal
  path_to_cop_xml: '../shared/data/cop_xml/*'
  salesforce:
    :host: 'test.salesforce.com'
    :username: 'salesforce@unglobalcompact.org.fgcfull'
    :password: 'UNGC2017!'
    :token: '3Zk0h535c2brvEEzF6gaDE4B'
    :client_id: '3MVG9Yb5IgqnkB4qIBUG7lt8Fq3edwKujcgHRMVLhiefQqDUsIHYkf_MFSzEKHJwdOr6IfI98PGantWvDmN9T'
    :client_secret: '4640851639819575954'

test:
  <<: *universal
  path_to_cop_xml: 'data/cop_xml'
  salesforce:
    :host: 'fake.salesforce.host'
    :username: 'username'
    :password: 'password'
    :token: 'token'
    :client_id: 'client_id'
    :client_secret: 'client_secret'

production:
  <<: *universal
  path_to_cop_xml: '../../shared/data/cop_xml/*'
  salesforce:
    :host: 'unglobalcompact.my.salesforce.com'
    :username: 'salesforce@unglobalcompact.org'
    :password: 'UNGC2017!'
    :token: 'zMhu9bdAj9BbTioxOnx1GYou'
    :client_id: '3MVG9yZ.WNe6byQA3.eubyLjVXu.C2uy4iK.BzfJQK._fMp.Uo1fSYe5rOaIfUiCLXOVpLyQjXds2eD6FaoCB'
    :client_secret: '3432384631816779467'

staging:
  <<: *universal
  salesforce:
    :host: 'test.salesforce.com'
    :username: 'salesforce@unglobalcompact.org.fgcfull'
    :password: 'UNGC2017!'
    :token: '3Zk0h535c2brvEEzF6gaDE4B'
    :client_id: '3MVG9Yb5IgqnkB4qIBUG7lt8Fq3edwKujcgHRMVLhiefQqDUsIHYkf_MFSzEKHJwdOr6IfI98PGantWvDmN9T'
    :client_secret: '4640851639819575954'
