universal: &universal
  ungc_organization_name: 'UNGC'
  local_network_guest_name: 'Local Network Guests'
  url_host: 'unglobalcompact.org'
  search_results_per_page: 25
  case_story_path: '/COP/Case_Story/case_search.html'
  cop_path: '/COP/index.html'
  cop_active_path: '/COP/analyzing_progress/active_cops.html'
  cop_advanced_path: '/COP/analyzing_progress/advanced_cops.html'
  cop_learner_path: '/COP/analyzing_progress/learner_cops.html'
  cop_expelled_path: '/COP/analyzing_progress/expelled_participants.html'
  cop_noncommunicating_path: '/COP/analyzing_progress/non_communicating.html'
  cop_notable_path: '/COP/analyzing_progress/notable_cops.html'
  cop_search_path: '/COP/cop_search.html'
  news_archive_path: '/NewsAndEvents/news_archives/index.html'
  news_headlines_path: '/NewsAndEvents/index.html'
  participant_search_path: '/participants/search'
  participant_lead_path: '/HowToParticipate/Lead/lead_participants.html'
  search_path: '/search'
  signup_form_path: '/HowToParticipate/How_To_Apply.html'
  upcoming_events_path: '/NewsAndEvents/Upcoming_Events.html'

development:
  test: thing
  path_to_cop_xml: '../shared/data/cop_xml/*'
  salesforce:
    :host: 'cs10.salesforce.com'
    :username: 'salesforce@unglobalcompact.org.ungc'
    :password: 'ungcsalesf0rce'
    :token: 'OIEWrN1BTDIA6myOErgpFAC1z'
    :client_id: '3MVG9_7ddP9KqTzclryJIYRb4uHK.TglmwbR319gFThGZoKE7KH615UxDdZ6lKL2.BVH4v1b_O0kSUqVM9_Rv'
    :client_secret: '6233031473623045146'
    :callback_url: 'https://www.unglobalcompact.org/salesforce/sync'
  <<: *universal

test:
  test: thing
  path_to_cop_xml: 'data/cop_xml'
  <<: *universal

production:
  test: thing
  path_to_cop_xml: '../../shared/data/cop_xml/*'
  salesforce:
    :host: 'na18.salesforce.com'
    :username: 'salesforce@unglobalcompact.org'
    :password: '5@l35f0rc3ungc'
    :token: 'FKyYPDzHNL4ETkE0w8dJh84b'
    :client_id: '3MVG9yZ.WNe6byQA3.eubyLjVXqbjVD.LVqC4SvP4zG6qovb77mwdCwgjK3mCXStC2TMqs17Q400NSGt6e.TK'
    :client_secret: '4153199578286720849'
    :callback_url: 'https://www.unglobalcompact.org/salesforce/sync'
  <<: *universal

staging:
  test: thing
  salesforce:
    :host: 'cs9.salesforce.com'
    :username: 'salesforce@unglobalcompact.org.ungcpd'
    :password: 'ungcsalesf0rce'
    :token: 'TCr6K80FgBjYvPt00b0THZg4P'
    :client_id: '3MVG9FS3IyroMOh4XgXDsHvL1ThrQWh1cSOiefSjIhvkjFohp1wkvDZNxpmrWOqB91amIItoj06Fgdjf59AAP'
    :client_secret: '7058664805928495003'
    :callback_url: 'https://staging.unglobalcompact.org/salesforce/sync'
  <<: *universal

preview:
  test: thing
  <<: *universal
