---
:concurrency: 2
:pidfile: tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
development:
  :concurrency: 1
  :logfile: null
staging:
  :concurrency: 2
production:
  :concurrency: 2
:queues:
  - default
  - mailers
