development:
  mem_limit: 32M
  max_matches: 15000
  utf8: false
test:
  mem_limit: 32M
  max_matches: 15000
  quiet_deltas: true
  utf8: false
preview:
  mem_limit: 32M
  max_matches: 15000
  utf8: false
staging:
  mem_limit: 32M
  max_matches: 15000
  quiet_deltas: true
  utf8: false
production:
  mem_limit: 32M
  max_matches: 15000
  quiet_deltas: true
  utf8: false
