common: &common
  mem_limit: 40M
  64bit_timestamps: true

development:
  <<: *common
test:
  <<: *common
  quiet_deltas: true
preview:
  <<: *common
  indices_location: /srv/unglobalcompact/shared/sphinx/preview
  configuration_file: /srv/unglobalcompact/shared/config/sphinx.conf
staging:
  <<: *common
  indices_location: /srv/unglobalcompact/shared/sphinx/staging
  configuration_file: /srv/unglobalcompact/shared/config/sphinx.conf
  quiet_deltas: true
production:
  <<: *common
  indices_location: /srv/unglobalcompact/shared/sphinx/production
  configuration_file: /srv/unglobalcompact/shared/config/sphinx.conf
  quiet_deltas: true
