development:
  mem_limit: 32M
  max_matches: 15000
test:
  mem_limit: 32M
  max_matches: 15000
  quiet_deltas: true
preview:
  mem_limit: 32M
  max_matches: 15000
staging:
  mem_limit: 32M
  max_matches: 15000
  quiet_deltas: true
production:
  mem_limit: 32M
  max_matches: 15000
  quiet_deltas: true

