#!/usr/bin/env ruby
require 'pathname'

APP_ROOT = Pathname.new File.expand_path('../../',  __FILE__)

Dir.chdir APP_ROOT do
  # This script is a starting point to setup your application.
  # Add necessary setup steps to this file:

  puts "== Installing dependencies =="
  system "brew install imagemagick openssl redis mysql@5.6 libyaml coreutils readline phantomjs"
  system "brew install sphinx --with-mysql"
  system "brew link mysql@5.6 --force"

  system "gem install bundler --conservative"
  system "bundle check || bundle install"

  puts "\n== Copying sample files =="
  unless File.exist?("config/database.yml")
    system "cp config/database.yml.sample config/database.yml"
  end

  unless File.exist?("config/secrets.yml")
    system "cp config/secrets.yml.example config/secrets.yml"
  end

  puts "\n== Removing old logs and tempfiles =="
  system "rm -f log/*"
  system "rm -rf tmp/cache"

  puts "\n== Preparing database =="
  system "killall searchd"
  system "bin/rake db:create db:schema:load search:rebuild"
end
