#!/usr/bin/env ruby

require "optparse"
require "fileutils"

download = false

option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{$0} DIRECTORY"

  opts.on "-d", "--download", "Download files instead of creating dummies" do |v|
    download = true
  end
end

begin
  option_parser.parse!
rescue OptionParser::ParseError => e
  puts e
  puts
  puts option_parser
  exit -1
end

dir = ARGV.first

if dir.nil? or dir.empty?
  puts option_parser
  exit -1
end

FileUtils.mkdir_p(dir)

require "uri"
require "open-uri"
require "hpricot"

puts "Downloading file list..."

uri  = URI.parse("http://gcln.unglobalcompact.org/UploadedDocument/")
page = open(uri)
doc  = Hpricot(page)

links = doc.search("a").map { |a| a.attributes["href"] }
links.reject! { |href| href.nil? or href.empty? or href == "/" }

puts "Found #{links.size} files"

links.each do |href|
  filename   = File.basename(URI.unescape(href))
  local_path = File.join(dir, filename)

  if File.exist?(local_path)
    puts "Already exists: #{filename}"
    next
  end

  content = if download
              puts "Downloading file: #{href}"
              response = Net::HTTP.get_response(uri.host, href)

              unless response.code.to_i == 200
                puts response.body
                puts "request failed with code #{response.code}"
                exit -1
              end

              response.body
            else
              puts "Creating dummy file: #{filename}"
              "hello world"
            end

  File.open(local_path, "w", encoding: "ASCII-8BIT") do |f|
    f.write(content)
  end
end
