#!/usr/bin/env ruby
ENV['RAILS_ENV'] = ARGV.first || ENV['RAILS_ENV'] || 'development'  
require File.dirname(__FILE__) + '/../config/environment' unless defined?(RAILS_ROOT)
require 'pp'

[Content, Navigation].each do |thing|
  puts "Clear #{thing.to_s}"
  thing.delete_all
  puts "Loading #{thing.to_s}"
  stuff = YAML.load_file(Dir["#{RAILS_ROOT}/db/yaml/#{thing.to_s}.*.yml"].last)
  stuff.each do |item|
    puts " creating #{thing} ##{item['id']}"
    thing.create item
  end
end