#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment' unless defined?(RAILS_ROOT)
require 'hpricot'
require 'pp'
require 'facets'
require 'import_helper'

# root = '/Users/joshua/Sites/unspace/demo.unglobalcompact.org/'
root = '/Users/joshua/Sites/unspace/opencms_export/unglobalcompact/'

Navigation.delete_all
filename = root + 'index.html'
$doc = Hpricot(open(filename))
($doc/'div#nav > ul > li').inject(0) do |i, elem|
  attrs = attributes_for_element elem
  children = attrs.delete(:children)
  attrs[:position] = i
  parent = Navigation.create attrs
  children.inject(0) do |j, child|
    Navigation.create child.merge(:parent_id => parent.id, :position => j)
    j += 1
  end
  i += 1
end

Content.delete_all
files = get_files_from(root)
files.each do |filename|
  # filename = root + 'index.html'
  puts "Reading from '#{filename}'"
  doc = Hpricot(open(filename))
  if filename == (root + 'index.html')
    content = home_page_content(doc)
  else
    content = regular_page_content(doc)
  end
  # pp content
  path = "/#{filename - root}"
  content = Content.create :content => content, :path => path
  # Navigation.find_all_by_href(path).each do |nav|
  #   nav.update_attribute(:content_id, content.id)
  # end
end
