#!/usr/bin/env ruby

unless (1..2) === ARGV.length
  puts "usage: #{$0} DATA_FILE [IMPORTER_CLASS]"
  exit -1
end

require File.expand_path(File.dirname(__FILE__) + "/../config/environment")
require "importers/local_networks"

Importers::LocalNetworks::Runner.new(*ARGV).run

