#!/usr/bin/env ruby
ENV['RAILS_ENV'] = ARGV.first || ENV['RAILS_ENV'] || 'development'  
require File.dirname(__FILE__) + '/../config/environment' unless defined?(RAILS_ROOT)
require 'ruby-debug'
require 'hpricot'
require 'replacement_helper'

replacements = load_replacements
replacements.each_pair do |path,new_content|
  if path_valid?(path)
    replace_contents(path, new_content)
  else
    puts "skipping #{path} - looks like something else?"
  end
end
create_new_local_network_pages(replacements)

install_event_calendar
rewrite_event_archives
archive_latest_headlines
rewrite_news_headlines
rewrite_homepage
rewrite_search_pages