#!/bin/sh

java -cp vendor/poi/poi-3.10-FINAL-20140208.jar:vendor/poi/poi-scratchpad-3.10-FINAL-20140208.jar:vendor/poi/poi-ooxml-3.10-FINAL-20140208.jar:vendor/poi/xmlbeans-2.3.0.jar:vendor/poi/dom4j-1.6.1.jar:vendor/poi/poi-ooxml-schemas-3.10-FINAL-20140208.jar:vendor/poi/ org/unglobalcompact/search/WordReader $@
