:domain: staging.ungc.managedmachine.com

:apache:
  :users:
    ungc: sustainability

:webdav:
  :domain: webdav-staging.unglobalcompact.org

:passenger:
  :max_pool_size: 1

:ssl:
  :only: true
  :certificate_file: /etc/ssl/www.unglobalcompact.org.crt
  :certificate_key_file: /etc/ssl/www.unglobalcompact.org.key
  :certificate_chain_file: /etc/ssl/NetworkSolutionsDVServerCA.crt
  :protocol: All -SSLv2 -SSLv3
