:domain: staging.ungc.managedmachine.com

:apache:
  :users:
    ungc: sustainability

:webdav:
  :domain: webdav-staging.unglobalcompact.org

:passenger:
  :max_pool_size: 1

:ssl:
  :only: true
  :certificate_file:  /etc/letsencrypt/live/staging.unglobalcompact.org/fullchain.pem 
  :certificate_key_file: /etc/letsencrypt/live/staging.unglobalcompact.org/privkey.pem
  :certificate_chain_file: /etc/letsencrypt/live/staging.unglobalcompact.org/chain.pem
  :protocol: All -SSLv2 -SSLv3
