:domain: staging.ungc.managedmachine.com

:webdav:
  :domain: webdav-staging.unglobalcompact.org

:passenger:
  :max_pool_size: 1

:ssl:
  :only: true
  :certificate_file: /etc/ssl/staging.unglobalcompact.org.crt
  :certificate_key_file: /etc/ssl/staging.unglobalcompact.org.key
  :certificate_chain_file: /etc/ssl/staging.unglobalcompact.org.crt
