---
- hosts: all
  become: true

  tasks:
    - name: Add repositories
      tags: prereqs
      apt_repository: repo={{item}} state=present
      with_items:
        - ppa:git-core/ppa
        - ppa:builds/sphinxsearch-rel22

    - name: Add recent node key
      tags: prereqs
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

    - name: Add node to the sources list
      tags: prereqs
      apt_repository: repo='deb https://deb.nodesource.com/node_0.10 precise main' state=present

    - name: Update apt cache
      tags: prereqs
      apt: update_cache=yes cache_valid_time=3600

    - name: Install prereqs
      tags: prereqs
      apt: name={{item}} state=latest
      with_items:
        - build-essential
        - git
        - nodejs
        - vim
        - libmysqlclient-dev
        - sphinxsearch
        - mysql-server
        - curl
        - python-mysqldb
        - redis-server
        - imagemagick
        - libmagickwand-dev
        - default-jre-headless
        - python-pdfminer

    - known_hosts:  name='github.com'
                    path='/home/vagrant/.ssh/ssh_known_hosts'
                    key="{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"

    - known_hosts:  name='unglobalcompact.org'
                    path='/home/vagrant/.ssh/ssh_known_hosts'
                    key="{{ lookup('pipe', 'ssh-keyscan -t rsa unglobalcompact.org') }}"

    - name: Create the MySQL user
      tags: mysql
      mysql_user: name=rails password=12345 priv=*.*:ALL state=present

    - name: Default to /vagrant
      tags: env
      lineinfile: dest="/home/vagrant/.bashrc"
                  line="cd /vagrant"

- hosts: all
  become: true

  roles:
    - williamyeh.reset-locale
    - rvm_io.rvm1-ruby

  vars:
    rvm1_install_path: '/home/vagrant/.rvm'
    rvm1_user: 'vagrant'
    rvm1_install_flags: '--auto-dotfiles --user-install'
    rvm1_rubies:
      - 'ruby-2.1.5'
    rvm1_gpg_key_server: 'hkp://pgp.mit.edu'

  tasks:
    - name: Remove sphinx start
      tags: sphinx
      lineinfile: dest=/etc/init/sphinxsearch.conf
                regexp="^start on*"
                line="# start on (net-device-up"

    - name: Remove sphinx start line 2
      tags: sphinx
      lineinfile: dest=/etc/init/sphinxsearch.conf
                regexp="^\s+and local-filesystems"
                line="#           and local-filesystems"

    - name: Remove sphinx start line 3
      tags: sphinx
      lineinfile: dest=/etc/init/sphinxsearch.conf
                regexp="^\s+and runlevel.*"
                line="# 	  and runlevel [2345])"

    - name: Remove sphinx stop
      tags: sphinx
      lineinfile: dest=/etc/init/sphinxsearch.conf
                regexp="^stop on.*"
                line="# stop on runlevel [016]"

    - name: Stop sphinx
      tags: sphinx
      service: name=sphinxsearch state=stopped

    - name: Install global npm packages
      tags: node
      npm: name={{item}} global=yes
      with_items:
        - bower
        - ember-cli
        - node-sass

    - name: Create a symlink pdf2txt
      tags: pdf
      file: src="/usr/bin/pdf2txt"
            dest="/usr/bin/pdf2txt.py"
            state=link

- hosts: all

  tasks:
    - name: Configure Ruby gems
      tags: ruby
      lineinfile: dest=/home/vagrant/.gemrc line={{item}} create=yes
      with_items:
        - "gem: --no-ri --no-rdoc"
        - "install: --no-rdoc --no-ri"
        - "update: --no-rdoc --no-ri"

    - name: Install ruby gems
      tags: ruby
      command: "/bin/bash -l -c 'cd /vagrant && bundle -j2'"

    - name: Create the development database
      tags: ruby
      command: "/bin/bash -l -c 'cd /vagrant && bin/rake db:drop db:create db:schema:load'"

    - name: Create the test database
      tags: ruby
      command: "/bin/bash -l -c 'cd /vagrant && RAILS_ENV=test bin/rake db:drop db:create db:test:prepare'"

    - name: Build the initial search index
      tags: ruby
      command: "/bin/bash -l -c 'cd /vagrant && bin/rake search:rebuild'"

    - name: Install npm dependencies
      tags: js
      command: "/bin/bash -l -c 'cd /vagrant/frontend/sitemap && npm install --no-bin-links'"

    - name: Install bower dependencies
      tags: js
      command: "/bin/bash -l -c 'cd /vagrant/frontend/sitemap && bower install'"

    - name: Build the ember app
      tags: js
      command: "/bin/bash -l -c 'cd /vagrant/frontend/sitemap && ember build'"
